language: node_js
node_js:
  - "10.14"
env:
  global:
    - FTP_HOST = $FTP_HOST
    - FTP_USER = $FTP_USER
    - FTP_PASSWORD = $FTP_PASSWORD
dist: trusty
sudo: required
branches:
  only:
    - master
install:
  - npm install
before_script:
  - npm run build-prod
script:
  - npm run deploy
