language: node_js
node_js:
  - "10.14"
dist: trusty
sudo: required
branches:
  only:
    - master
install:
  - echo ${DENEME_ENV}
  - npm install
before_script:
  - npm run build-prod
script:
  - npm run deploy
