language: node_js
node_js:
  - "10.14"
dist: trusty
sudo: required
branches:
  only:
    - master
install:
  - npm install
before_script:
  - npm run build-prod
script:
  - node deploy.js ftpHost=FTP_HOST ftpUser=FTP_USER ftpPassword=FTP_PASSWORD
